### ISSUE TITLE
non-printable text in web-generated feff.inp

### ISSUE THREAD

**Issue by newville** [bruceravel/WebAtoms#1]
The feff.inp files generated by WebAtoms seem to start with characters 
  
    239, 187, 191, 32, 32, 10

as an extra first line, which prevents feff6l and feff8l from being able to run with such files.

I haven't investigated further.

**Comment by bruceravel** [comment]
Cool!  I'll look into it.

**Comment by bruceravel** [comment]
Fixed, I think, in d6c18f2413034a96410b33153caf1045b04b3285

**Comment by newville** [comment]
Yep, that fixed it.  Website updated.
