### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by FelixThiel** [bruceravel/WebAtoms#2]
Dear Mr. Ravel,

I am sorry to let you know, that I can not access WebAtoms under "http://millenia.cars.aps.anl.gov/webatoms/", due to an "Internal Server Error".
I hope it is possible to fix this issue, as the application is very helpful to my work and has already been a great tool!

Best regards,
Felix Thiel

![internalservererror](https://user-images.githubusercontent.com/31767795/30211487-87bf0ea4-94a1-11e7-8979-3772d2b3737e.PNG)

**Comment by newville** [comment]
@FelixThiel @bruceravel  Sorry -- this was my fault. but I believe it is now working OK.

I upgraded the OS on the server, but several Perl packages that are needed for Demeter were then left in a broken state.    It's not an actual problem with the WebAtoms code,  just a lack of re-configuring perl modules for demeter and testing after rebuilding the server.
