### ISSUE TITLE
Webatoms problems for large clusters

### ISSUE THREAD

**Issue by ajgausa** [bruceravel/WebAtoms#5]
Dear Bruce,
I'm trying to generate some feff.inp files for LDOS calculation on very large clusters, typically some thousands of atoms. When using large values for the cluster size, webatoms seems to do strange things.

For example, for a Ni crystal in the fcc Fm3m structrure with a_0=3.52 A, when I go up 30 A in the cluster size, the result seems OK and the shells are ordered by increasing distance to the central atom. However, if I use a value of 35 A, I get some strange results, even the shells are not properly ordered and it seems that some of them contain too many atoms.

Any clues of what is going on would be greatly appreciated.

Thanks in advance for your help.

Best,

Angel

**Comment by bruceravel** [comment]
What's going on is pretty simple.  You are trying to use the wrong tool for a job.  Kind of like using a hammer to pound in a screw.

The purpose of Atoms is turn crystal data into a list of atomic coordinates.  You already have a list of atomic coordinates.  Atoms doesn't do ... doesn't _claim_ to do anything to help you run Feff on a cluster.

What you almost certainly want to do is follow the example of this talk:

https://speakerdeck.com/bruceravel/modeling-non-crystalline-samples 

You have a cluster, what you want to do add the boilerplate to your cluster of atoms such that Feff will run correctly.  That's not a hard job to do by hand or to write a small program/script to take care of for you.  It's just not what Atoms is intended to do.

I understand that you are saying that your cluster represents a very large, P1 primitive cell.  As such, you should be able to have Atoms do the job of adding Feff's boilerplate.  That's not exactly wrong, but it is also not exactly wrong to say that if you hit a screw hard enough with a hammer, it _will_ go into a piece of wood....
